Hw11
KanKori/JavaCourse pull request #3
Opened 2022-07-08 20:42 UTC by KanKori

2022-07-08 22:17 UTC, Fabolo12 requested changes
Написанные тесты без ошибок, но я не вижу выполнения вот этого задания:
Хотя-бы по одному примеру:
ArgumentMatchers 
verify times
Calling real methods
THROWING EXCEPTIONS

2022-07-16 19:48 UTC, Fabolo12 approved these changes

2022-07-16 19:48 UTC, Fabolo12 commented on src/test/java/repository/LaptopRepositoryTest.java
> +    }
А что этот тест проверяет? 
И мы не мокируем класс который тестируем

2022-07-16 19:48 UTC, Fabolo12 commented on src/test/java/service/LaptopServiceTest.java
> +        verify(repository).save(updatedLaptop);
Тут как-то много лишних действий

2022-07-16 20:24 UTC, KanKori commented on src/test/java/repository/LaptopRepositoryTest.java
> +    }
Проверяет можем ли мы к моку применить метод findById

2022-07-21 14:10 UTC, merged